<template>
  <BaseLayout>
    <template #content>
      <div class="admin-reports">
        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
          <div>
            <h1 class="text-3xl font-bold text-gray-900">System Reports</h1>
            <p class="mt-1 text-gray-600">
              Generate and download system reports and analytics
            </p>
          </div>
          <div class="flex gap-3">
            <Button
              icon="pi pi-refresh"
              label="Refresh"
              :loading="reportsLoading"
              @click="loadReportTypes"
              class="p-button-outlined"
            />
          </div>
        </div>

        <!-- Report Categories -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
          <Card
            v-for="report in reportTypes"
            :key="report.id"
            class="border-0 shadow-lg cursor-pointer hover:shadow-xl transition-shadow"
            @click="selectReport(report)"
          >
            <template #content>
              <div class="space-y-3">
                <div class="flex items-center justify-between">
                  <div
                    :class="{
                      'bg-blue-100 text-blue-600': report.category === 'Applications',
                      'bg-green-100 text-green-600': report.category === 'Placements',
                      'bg-purple-100 text-purple-600': report.category === 'Capacity',
                      'bg-orange-100 text-orange-600': report.category === 'System'
                    }"
                    class="w-12 h-12 rounded-lg flex items-center justify-center"
                  >
                    <i :class="`pi pi-${getReportIcon(report.icon)}`" class="text-xl"></i>
                  </div>
                  <div class="text-xs text-gray-500">
                    {{ report.category }}
                  </div>
                </div>

                <div>
                  <h3 class="font-semibold text-gray-900 mb-1">{{ report.name }}</h3>
                  <p class="text-sm text-gray-600">{{ report.description }}</p>
                </div>

                <div v-if="report.lastGenerated" class="text-xs text-gray-500">
                  Last generated: {{ formatDate(report.lastGenerated) }}
                </div>

                <div class="flex justify-end">
                  <Button
                    label="Generate"
                    class="p-button-sm p-button-primary"
                    @click.stop="selectReport(report)"
                  />
                </div>
              </div>
            </template>
          </Card>
        </div>

        <!-- Recent Reports -->
        <Card v-if="generatedReports.length > 0" class="mb-6">
          <template #title>
            <div class="flex items-center gap-2">
              <i class="pi pi-download text-blue-600"></i>
              Recent Reports
            </div>
          </template>
          <template #content>
            <DataTable
              :value="generatedReports"
              :paginator="true"
              :rows="10"
              responsive-layout="scroll"
              class="p-datatable-sm"
            >
              <Column field="name" header="Report Name" sortable>
                <template #body="{ data }">
                  <div class="font-medium">{{ data.name }}</div>
                  <div class="text-sm text-gray-500">{{ data.type }}</div>
                </template>
              </Column>
              <Column field="generatedBy" header="Generated By" sortable />
              <Column field="date" header="Date" sortable>
                <template #body="{ data }">
                  {{ formatDate(data.date) }}
                </template>
              </Column>
              <Column field="size" header="Size" />
              <Column field="format" header="Format">
                <template #body="{ data }">
                  <Tag
                    :value="data.format.toUpperCase()"
                    :class="{
                      'p-tag-info': data.format === 'pdf',
                      'p-tag-success': data.format === 'excel',
                      'p-tag-warning': data.format === 'csv'
                    }"
                  />
                </template>
              </Column>
              <Column header="Actions">
                <template #body="{ data }">
                  <Button
                    icon="pi pi-download"
                    class="p-button-sm p-button-outlined"
                    @click="downloadReport(data)"
                    v-tooltip="'Download Report'"
                  />
                </template>
              </Column>
            </DataTable>
          </template>
        </Card>

        <!-- Report Generation Dialog -->
        <Dialog
          v-model:visible="showGenerateDialog"
          :style="{ width: '600px' }"
          header="Generate Report"
          :modal="true"
          class="p-fluid"
        >
          <div v-if="selectedReport" class="space-y-4">
            <div>
              <h3 class="font-semibold text-lg">{{ selectedReport.name }}</h3>
              <p class="text-gray-600">{{ selectedReport.description }}</p>
            </div>

            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                  Start Date
                </label>
                <Calendar
                  v-model="reportParams.startDate"
                  date-format="yy-mm-dd"
                  class="w-full"
                  placeholder="Select start date"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                  End Date
                </label>
                <Calendar
                  v-model="reportParams.endDate"
                  date-format="yy-mm-dd"
                  class="w-full"
                  placeholder="Select end date"
                />
              </div>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                Format
              </label>
              <Dropdown
                v-model="reportParams.format"
                :options="formatOptions"
                option-label="label"
                option-value="value"
                class="w-full"
                placeholder="Select format"
              />
            </div>

            <!-- Additional filters based on report type -->
            <div v-if="selectedReport.category === 'Applications'" class="space-y-3">
              <h4 class="font-medium text-gray-900">Application Filters</h4>
              <div class="grid grid-cols-2 gap-4">
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">
                    Status
                  </label>
                  <MultiSelect
                    v-model="reportParams.applicationStatuses"
                    :options="applicationStatusOptions"
                    option-label="label"
                    option-value="value"
                    placeholder="Select statuses"
                    class="w-full"
                  />
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">
                    District
                  </label>
                  <Dropdown
                    v-model="reportParams.district"
                    :options="districtOptions"
                    option-label="label"
                    option-value="value"
                    placeholder="All districts"
                    class="w-full"
                    show-clear
                  />
                </div>
              </div>
            </div>

            <div v-if="selectedReport.category === 'Capacity'" class="space-y-3">
              <h4 class="font-medium text-gray-900">Capacity Filters</h4>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">
                  Include Kindergartens
                </label>
                <MultiSelect
                  v-model="reportParams.kindergartens"
                  :options="kindergartenOptions"
                  option-label="label"
                  option-value="value"
                  placeholder="All kindergartens"
                  class="w-full"
                />
              </div>
            </div>
          </div>

          <template #footer>
            <Button
              label="Cancel"
              icon="pi pi-times"
              class="p-button-outlined"
              @click="showGenerateDialog = false"
            />
            <Button
              label="Generate Report"
              icon="pi pi-check"
              :loading="generating"
              @click="generateReport"
            />
          </template>
        </Dialog>

        <!-- Loading overlay -->
        <div
          v-if="generating"
          class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
        >
          <Card class="p-6">
            <template #content>
              <div class="flex items-center gap-4">
                <ProgressSpinner class="w-8 h-8" />
                <div>
                  <div class="font-medium">Generating Report...</div>
                  <div class="text-sm text-gray-600">This may take a few moments</div>
                </div>
              </div>
            </template>
          </Card>
        </div>

        <!-- Toast for notifications -->
        <Toast />
      </div>
    </template>
  </BaseLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useToast } from 'primevue/usetoast'
import BaseLayout from '@/layouts/core/BaseLayout.vue'
import { useAdmin } from '@/composables/api/useAdmin'
import type { ReportType, ReportGenerationRequest, GeneratedReport } from '@/types/admin'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import Calendar from 'primevue/calendar'
import Dropdown from 'primevue/dropdown'
import MultiSelect from 'primevue/multiselect'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Tag from 'primevue/tag'
import ProgressSpinner from 'primevue/progressspinner'
import Toast from 'primevue/toast'

const toast = useToast()

const {
  reportTypes,
  reportsLoading,
  loadReportTypes,
  generateReport: generateReportApi
} = useAdmin()

// Local state
const selectedReport = ref<ReportType | null>(null)
const showGenerateDialog = ref(false)
const generating = ref(false)
const generatedReports = ref<GeneratedReport[]>([])

// Report parameters
const reportParams = ref({
  startDate: null as Date | null,
  endDate: null as Date | null,
  format: 'pdf' as 'pdf' | 'excel' | 'csv',
  applicationStatuses: [] as string[],
  district: null as string | null,
  kindergartens: [] as string[]
})

// Options for dropdowns
const formatOptions = [
  { label: 'PDF', value: 'pdf' },
  { label: 'Excel', value: 'excel' },
  { label: 'CSV', value: 'csv' }
]

const applicationStatusOptions = [
  { label: 'Submitted', value: 'submitted' },
  { label: 'Under Review', value: 'under_review' },
  { label: 'Approved', value: 'approved' },
  { label: 'Rejected', value: 'rejected' },
  { label: 'Waitlisted', value: 'waitlisted' }
]

const districtOptions = [
  { label: 'Gamle Oslo', value: 'gamle-oslo' },
  { label: 'Grünerløkka', value: 'grunerløkka' },
  { label: 'Sagene', value: 'sagene' },
  { label: 'St. Hanshaugen', value: 'st-hanshaugen' },
  { label: 'Frogner', value: 'frogner' }
]

const kindergartenOptions = [
  { label: 'Løvenskiold Kindergarten', value: 'lovenskiold' },
  { label: 'Bjørn West Kindergarten', value: 'bjorn-west' },
  { label: 'Rainbow Kindergarten', value: 'rainbow' }
]

// Initialize data on mount
onMounted(async () => {
  await loadReportTypes()
  // Set default date range to last 30 days
  const endDate = new Date()
  const startDate = new Date()
  startDate.setDate(startDate.getDate() - 30)
  reportParams.value.startDate = startDate
  reportParams.value.endDate = endDate
})

// Methods
const selectReport = (report: ReportType) => {
  selectedReport.value = report
  showGenerateDialog.value = true
  // Reset parameters
  reportParams.value.applicationStatuses = []
  reportParams.value.district = null
  reportParams.value.kindergartens = []
}

const generateReport = async () => {
  if (!selectedReport.value || !reportParams.value.startDate || !reportParams.value.endDate) {
    toast.add({
      severity: 'warn',
      summary: 'Missing Information',
      detail: 'Please select date range and format',
      life: 3000
    })
    return
  }

  generating.value = true

  try {
    const request: ReportGenerationRequest = {
      reportId: selectedReport.value.id,
      dateRange: {
        start: reportParams.value.startDate.toISOString().split('T')[0],
        end: reportParams.value.endDate.toISOString().split('T')[0]
      },
      format: reportParams.value.format,
      filters: {
        applicationStatuses: reportParams.value.applicationStatuses,
        district: reportParams.value.district,
        kindergartens: reportParams.value.kindergartens
      }
    }

    const report = await generateReportApi(request)

    if (report) {
      generatedReports.value.unshift(report)
      showGenerateDialog.value = false

      toast.add({
        severity: 'success',
        summary: 'Report Generated',
        detail: `${selectedReport.value.name} has been generated successfully`,
        life: 5000
      })

      // Auto-download if it's a small report
      if (report.downloadUrl) {
        setTimeout(() => {
          window.open(report.downloadUrl, '_blank')
        }, 1000)
      }
    }
  } catch (error) {
    toast.add({
      severity: 'error',
      summary: 'Generation Failed',
      detail: 'Failed to generate report. Please try again.',
      life: 5000
    })
  } finally {
    generating.value = false
  }
}

const downloadReport = (report: GeneratedReport) => {
  if (report.downloadUrl) {
    window.open(report.downloadUrl, '_blank')
  } else {
    toast.add({
      severity: 'warn',
      summary: 'Download Unavailable',
      detail: 'Report download link is not available',
      life: 3000
    })
  }
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('no-NO', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const getReportIcon = (icon: string): string => {
  const iconMap: Record<string, string> = {
    'FileText': 'file-text',
    'TrendingUp': 'trending-up',
    'Building': 'building',
    'BarChart': 'chart-bar'
  }
  return iconMap[icon] || 'file'
}
</script>

<style scoped>
.admin-reports {
  @apply p-6 max-w-7xl mx-auto;
}

.admin-reports .p-card {
  @apply transition-all duration-200;
}

.admin-reports .p-card:hover {
  @apply transform -translate-y-1;
}
</style>
